package week2HW3;
import java.util.Scanner;

public class Person {
	
	// - Class needs to have a parameterized constructor
	// - 2 child classes: Student and Employee
	// - Children will use similar structure for local parameters 
	// - Both children use objects to set data(generated by user)
	
	// Scanner for obj creation
	Scanner userScan = new Scanner(System.in);
	
	// Constructor parameters
	String fName = userScan.next();
	String lName;
	int age;
	char gender;
	String address;
	
	// Tracker for total people
	static int totalP;
	
	
	
	public Person()
	{
		totalP++;
	}
	
	public Person(String fName, String lName, int age, char gender, String address)
	{
		this.fName = fName;
		this.lName = lName;
		this.age = age;
		this.gender = gender;
		this.address = address;
		totalP++;
	}
	
	
	// "Auxiliary" constructors to compensate for any obj created with "missing information" 
	public Person(String fName, String lName, int age, char gender)
	{
		this.fName = fName;
		this.lName = lName;
		this.age = age;
		this.gender = gender;
		totalP++;
	}
	
	public Person(String fName, String lName, int age)
	{
		this.fName = fName;
		this.lName = lName;
		this.age = age;
		totalP++;
	}
	
	public Person(String fName, String lName, String address)
	{
		this.fName = fName;
		this.lName = lName;
		this.address = address;
		totalP++;
	}
	
	public Person(String fName, String lName)
	{
		this.fName = fName;
		this.lName = lName;
		totalP++;
	}
	
	public Person(String fName, int age)
	{
		this.fName = fName;
		this.age = age;
		totalP++;
	}
	
	
	// - "Spot checks" to ensure parameters were set correctly
	public void display()
	{
		System.out.println("Name: " + this.lName  + ", " + this.fName);
		System.out.println("Age: " + this.age);
		System.out.println("Gender: " + this.gender);
	}
	
	public void display (Person obj)
	{
		System.out.println("Parameterized Display");
		System.out.println("---------------------------");
		System.out.println("Name: " + obj.fName);
	}
	
//	Scanner userScan = new Scanner(System.in);
	
	

}
